//! Aero FFI Module — standardized zero-allocation bytecode bridge.
//! Auto-generated by aero-autodev. Module: $aeroc_module
//!
//! Hot-path execution is dispatched to the AeroVM across an `extern "C"`
//! boundary using raw, caller-owned pointers (`*mut std::ffi::c_void`). The VM
//! borrows the buffers but never frees them, so host lifetimes and 8-byte f64
//! alignment are preserved. Access is serialized through a thread-safe
//! `OnceLock<Mutex<..>>` handle.
//!
//! The `aero_vm_link` cfg gate selects the production dispatch path; the
//! default (verification) build keeps the bit-identical legacy stubs.
#![allow(dead_code)]
#![allow(unexpected_cfgs)]

use std::ffi::c_void;
use std::sync::{Mutex, OnceLock};

/// Opaque, thread-safe handle to the loaded AeroVM bytecode module.
struct AeroModuleHandle {
    loaded: bool,
}

impl AeroModuleHandle {
    const fn new() -> Self {
        Self { loaded: false }
    }

    fn ensure_loaded(&mut self) {
        if !self.loaded {
            // In production this loads `$aeroc_module` into the AeroVM runtime.
            self.loaded = true;
        }
    }
}

impl Drop for AeroModuleHandle {
    fn drop(&mut self) {
        // Release the AeroVM handle — prevents leaks across host teardown.
        self.loaded = false;
    }
}

static MODULE: OnceLock<Mutex<AeroModuleHandle>> = OnceLock::new();

fn module() -> &'static Mutex<AeroModuleHandle> {
    MODULE.get_or_init(|| Mutex::new(AeroModuleHandle::new()))
}

// ---- extern "C" AeroVM runtime linkage (raw pointer mapping) ----

extern "C" {
    /// Execute translated node `node_id` in the AeroVM runtime.
    ///
    /// `input`/`output` are raw, caller-owned buffers reinterpreted as
    /// `*const f64` / `*mut f64`. Ownership never transfers, so the host
    /// retains lifetime control and f64 alignment is guaranteed by the
    /// originating slices.
    fn aero_vm_execute_node(
        node_id: u32,
        input: *const c_void,
        input_len: usize,
        output: *mut c_void,
        output_cap: usize,
    ) -> i64;
}

/// Stack scratch capacity for the zero-allocation FFI call frame.
const AERO_NODE_CAP: usize = $AERO_NODE_CAP;

/// Zero-allocation dispatch into the AeroVM (enabled with the `aero_vm_link`
/// feature in production). Marshals the borrowed slice into raw pointers using
/// a stack-allocated output buffer — no heap allocation on the call path.
#[cfg(feature = "aero_vm_link")]
unsafe fn dispatch_node(node_id: u32, input: &[f64]) -> Result<Vec<f64>, String> {
    let mut scratch = [0.0f64; AERO_NODE_CAP]; // stack-allocated, zero heap
    let written = aero_vm_execute_node(
        node_id,
        input.as_ptr() as *const c_void,
        input.len(),
        scratch.as_mut_ptr() as *mut c_void,
        scratch.len(),
    );
    if written < 0 {
        return Err(format!("AeroVM node {{node_id}} failed (code {{written}})"));
    }
    Ok(scratch[..written as usize].to_vec())
}

