# -*- coding: utf-8 -*-
"""Python target emitter -- translates UAST nodes into Python 3 source code."""

from __future__ import annotations

from typing import Any, Dict, List

from .base import BaseEmitter, EmitterRegistry


class PythonEmitter(BaseEmitter):
    """Emit syntactically valid Python 3 source from a UAST node list."""

    target_language = "python"

    # ------------------------------------------------------------------
    # Preamble / postamble
    # ------------------------------------------------------------------

    def _emit_preamble(self) -> None:
        self._write_raw('"""Auto-generated by AeroNova polyglot emitter."""')
        self._blank()

    # ------------------------------------------------------------------
    # Declarations
    # ------------------------------------------------------------------

    def _emit_function_declaration(self, node: Dict[str, Any]) -> None:
        name = self._extract_name(node)
        params = self._extract_parameters(node)
        ret_type = self._extract_return_type(node)

        param_strs: List[str] = []
        for pname, ptype in params:
            if ptype:
                param_strs.append(f"{pname}: {self._map_type(ptype)}")
            else:
                param_strs.append(pname)

        sig = f"def {name}({', '.join(param_strs)})"
        if ret_type:
            sig += f" -> {self._map_type(ret_type)}"
        sig += ":"

        self._blank()
        self._write(sig)
        self._indent()

        body = self._extract_body_statements(node)
        if body:
            self._emit_body(body)
        else:
            self._write("pass")

        self._dedent()

    def _emit_type_declaration(self, node: Dict[str, Any]) -> None:
        name = self._extract_name(node)
        self._blank()
        self._write(f"class {name}:")
        self._indent()

        body = self._extract_body_statements(node)
        if body:
            self._emit_body(body)
        else:
            self._write("pass")

        self._dedent()

    def _emit_import_declaration(self, node: Dict[str, Any]) -> None:
        text = self._node_text(node).strip()
        if text.startswith(("import ", "from ")):
            self._write(text)
        elif text.startswith("#include") or text.startswith("use "):
            module = text.replace("#include", "").replace("use ", "").strip()
            module = module.strip("<>\";")
            self._write(f"import {module}")
        else:
            self._write(f"import {text}")

    def _emit_statement(self, node: Dict[str, Any]) -> None:
        text = self._node_text(node).strip()
        if text:
            self._write(self._translate_statement(text))

    def _emit_expression(self, node: Dict[str, Any]) -> None:
        text = self._node_text(node).strip()
        if text:
            self._write(text)

    def _emit_variable_declaration(self, node: Dict[str, Any]) -> None:
        name = self._extract_name(node)
        type_hint = self._extract_type_annotation(node)
        value = self._extract_initializer(node)

        if type_hint and value:
            self._write(f"{name}: {self._map_type(type_hint)} = {value}")
        elif value:
            self._write(f"{name} = {value}")
        elif type_hint:
            self._write(f"{name}: {self._map_type(type_hint)}")
        else:
            self._write(f"{name} = None")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _emit_body(self, statements: List[Dict[str, Any]]) -> None:
        emitted = False
        for stmt in statements:
            if not stmt.get("named", False):
                continue
            category = stmt.get("category", "")
            canonical = stmt.get("canonical_kind", "")
            if category in ("COMMENT", "PUNCTUATION"):
                continue
            self._emit_node(stmt["id"])
            emitted = True
        if not emitted:
            self._write("pass")

    def _translate_statement(self, text: str) -> str:
        text = text.rstrip(";")
        return text

    def _extract_initializer(self, node: Dict[str, Any]) -> str:
        for cid in node.get("children", []):
            child = self.nodes[cid]
            if child.get("category") in ("EXPRESSION", "LITERAL"):
                return self._node_text(child)
        return ""

    def _map_type(self, type_str: str) -> str:
        """Map C/Rust/Fortran types to Python type annotations."""
        type_map = {
            "int": "int",
            "i32": "int",
            "i64": "int",
            "u32": "int",
            "u64": "int",
            "usize": "int",
            "isize": "int",
            "float": "float",
            "f32": "float",
            "f64": "float",
            "double": "float",
            "char": "str",
            "str": "str",
            "&str": "str",
            "String": "str",
            "bool": "bool",
            "void": "None",
            "()": "None",
            "Vec": "list",
            "vector": "list",
            "HashMap": "dict",
            "map": "dict",
        }
        stripped = type_str.strip()
        return type_map.get(stripped, stripped)


EmitterRegistry.register("python", PythonEmitter)
