# -*- coding: utf-8 -*-
"""Rust target emitter -- translates UAST nodes into Rust source code."""

from __future__ import annotations

from typing import Any, Dict, List

from .base import BaseEmitter, EmitterRegistry


class RustEmitter(BaseEmitter):
    """Emit syntactically valid Rust source from a UAST node list."""

    target_language = "rust"

    # ------------------------------------------------------------------
    # Preamble / postamble
    # ------------------------------------------------------------------

    def _emit_preamble(self) -> None:
        self._write_raw("// Auto-generated by AeroNova polyglot emitter.")
        self._blank()

    # ------------------------------------------------------------------
    # Declarations
    # ------------------------------------------------------------------

    def _emit_function_declaration(self, node: Dict[str, Any]) -> None:
        name = self._extract_name(node)
        params = self._extract_parameters(node)
        ret_type = self._extract_return_type(node)

        param_strs: List[str] = []
        for pname, ptype in params:
            if pname == "self":
                param_strs.append("&self")
            elif ptype:
                param_strs.append(f"{pname}: {self._map_type(ptype)}")
            else:
                param_strs.append(f"{pname}: ()")

        sig = f"fn {name}({', '.join(param_strs)})"
        if ret_type and ret_type not in ("void", "None", "()"):
            sig += f" -> {self._map_type(ret_type)}"

        self._blank()
        self._write(f"pub {sig} {{")
        self._indent()

        body = self._extract_body_statements(node)
        if body:
            self._emit_body(body)
        else:
            self._write("todo!()")

        self._dedent()
        self._write("}")

    def _emit_type_declaration(self, node: Dict[str, Any]) -> None:
        name = self._extract_name(node)
        self._blank()
        self._write(f"pub struct {name} {{")
        self._indent()

        body = self._extract_body_statements(node)
        if body:
            self._emit_struct_fields(body)
        else:
            self._write("// empty")

        self._dedent()
        self._write("}")

    def _emit_import_declaration(self, node: Dict[str, Any]) -> None:
        text = self._node_text(node).strip()
        if text.startswith("use "):
            self._write(f"{text};")
        elif text.startswith("#include") or text.startswith("import ") or text.startswith("from "):
            module = text.replace("#include", "").replace("import ", "").replace("from ", "")
            module = module.strip("<>\"; ").replace(".", "::")
            self._write(f"use {module};")
        else:
            self._write(f"use {text};")

    def _emit_statement(self, node: Dict[str, Any]) -> None:
        text = self._node_text(node).strip()
        if text:
            translated = self._translate_statement(text)
            if translated and not translated.endswith((";", "}", "{")):
                translated += ";"
            self._write(translated)

    def _emit_expression(self, node: Dict[str, Any]) -> None:
        text = self._node_text(node).strip()
        if text:
            self._write(f"{text};")

    def _emit_variable_declaration(self, node: Dict[str, Any]) -> None:
        name = self._extract_name(node)
        type_hint = self._extract_type_annotation(node)
        value = self._extract_initializer(node)

        if type_hint and value:
            self._write(f"let {name}: {self._map_type(type_hint)} = {value};")
        elif value:
            self._write(f"let {name} = {value};")
        elif type_hint:
            self._write(f"let {name}: {self._map_type(type_hint)};")
        else:
            self._write(f"let {name};")

    def _emit_module_declaration(self, node: Dict[str, Any]) -> None:
        name = self._extract_name(node)
        self._blank()
        self._write(f"pub mod {name} {{")
        self._indent()

        body = self._extract_body_statements(node)
        if body:
            self._emit_body(body)

        self._dedent()
        self._write("}")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _emit_body(self, statements: List[Dict[str, Any]]) -> None:
        emitted = False
        for stmt in statements:
            if not stmt.get("named", False):
                continue
            category = stmt.get("category", "")
            if category in ("COMMENT", "PUNCTUATION"):
                continue
            self._emit_node(stmt["id"])
            emitted = True
        if not emitted:
            self._write("todo!()")

    def _emit_struct_fields(self, statements: List[Dict[str, Any]]) -> None:
        for stmt in statements:
            if not stmt.get("named", False):
                continue
            category = stmt.get("category", "")
            if category in ("COMMENT", "PUNCTUATION"):
                continue
            name = self._extract_name(stmt)
            type_hint = self._extract_type_annotation(stmt)
            if name and name not in ("{", "}"):
                mapped = self._map_type(type_hint) if type_hint else "()"
                self._write(f"pub {name}: {mapped},")

    def _translate_statement(self, text: str) -> str:
        text = text.rstrip(";")
        if text.startswith("print(") or text.startswith("print "):
            content = text.replace("print(", "").rstrip(")")
            return f'println!("{{}}", {content})'
        return text

    def _extract_initializer(self, node: Dict[str, Any]) -> str:
        for cid in node.get("children", []):
            child = self.nodes[cid]
            if child.get("category") in ("EXPRESSION", "LITERAL"):
                return self._node_text(child)
        return ""

    def _map_type(self, type_str: str) -> str:
        """Map Python/C/Fortran types to Rust types."""
        type_map = {
            "int": "i64",
            "float": "f64",
            "double": "f64",
            "str": "String",
            "string": "String",
            "bool": "bool",
            "void": "()",
            "None": "()",
            "list": "Vec<()>",
            "dict": "HashMap<String, ()>",
            "char": "char",
            "unsigned int": "u64",
            "long": "i64",
            "short": "i16",
            "size_t": "usize",
        }
        stripped = type_str.strip()
        return type_map.get(stripped, stripped)


EmitterRegistry.register("rust", RustEmitter)
